# Generated by Django 2.1.7 on 2019-04-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disorder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pmid', models.CharField(max_length=30)),
                ('design', models.CharField(max_length=30)),
                ('type_of_study', models.CharField(max_length=30)),
                ('ascertainment', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=30)),
                ('the_domain', models.CharField(max_length=30)),
                ('num_SNPs', models.IntegerField()),
                ('num_polys', models.IntegerField()),
                ('DX', models.CharField(max_length=30)),
                ('Case_N', models.IntegerField()),
                ('Case_perc_fem', models.FloatField()),
                ('Case_age', models.FloatField()),
                ('Control_N', models.IntegerField()),
                ('Control_perc_fem', models.FloatField()),
                ('Control_age', models.FloatField()),
                ('num_families', models.IntegerField()),
                ('num_affected', models.IntegerField()),
                ('num_generations', models.IntegerField()),
                ('mean_score', models.FloatField()),
                ('SD_score', models.FloatField()),
                ('measure_used', models.CharField(max_length=30)),
                ('disorder', models.CharField(max_length=30)),
                ('test', models.CharField(max_length=30)),
                ('hyperlink', models.CharField(max_length=30)),
            ],
        ),
    ]
