# Generated by Django 2.1.7 on 2019-04-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='analyzed',
            fields=[
                ('study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examples.study')),
            ],
        ),
        migrations.CreateModel(
            name='features',
            fields=[
                ('study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examples.study')),
            ],
        ),
        migrations.CreateModel(
            name='gene',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('ensmbl_id', models.IntegerField()),
                ('gene_chr', models.CharField(max_length=30)),
                ('gene_band', models.CharField(max_length=30)),
                ('gene_start', models.IntegerField()),
                ('gene_end', models.IntegerField()),
                ('gene_risk_status', models.CharField(max_length=30)),
                ('hyperlink', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='related_to',
            fields=[
                ('disorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examples.disorder')),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('SNP_id', models.CharField(max_length=30)),
                ('Meta_p_value', models.FloatField()),
                ('chromosome_location', models.CharField(max_length=30)),
                ('chromosome_band', models.CharField(max_length=30)),
                ('position', models.IntegerField()),
                ('version', models.CharField(max_length=30)),
                ('odds_risk', models.FloatField()),
                ('odds_risk_lci', models.FloatField()),
                ('odds_risk_uci', models.FloatField()),
                ('ethnicity_1000_pop', models.CharField(max_length=30)),
                ('REF_allele', models.CharField(max_length=30)),
                ('ALT_allele', models.CharField(max_length=30)),
                ('EFF_score', models.FloatField()),
                ('EFF_var', models.FloatField()),
                ('mtc_pvalue', models.FloatField()),
                ('snp_risk', models.CharField(max_length=30)),
                ('test', models.CharField(max_length=30)),
                ('hyperlink', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='has_a',
            fields=[
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examples.gene')),
                ('SNP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.SNP', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='related_to',
            name='SNP_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.SNP', unique=True),
        ),
        migrations.AddField(
            model_name='features',
            name='gene_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.gene', unique=True),
        ),
        migrations.AddField(
            model_name='analyzed',
            name='SNP_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.SNP', unique=True),
        ),
    ]
