# Generated by Django 2.1.7 on 2019-09-23 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_auto_20190420_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNP_entry',
            fields=[
                ('enrty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('SNP_id', models.CharField(max_length=30)),
                ('Meta_p_value', models.FloatField()),
                ('SNP_chromosome_location', models.CharField(max_length=30)),
                ('SNP_chromosome_band', models.CharField(max_length=30)),
                ('SNP_position', models.IntegerField()),
                ('SNP_version', models.CharField(max_length=30)),
                ('odds_risk', models.FloatField()),
                ('odds_risk_lci', models.FloatField()),
                ('odds_risk_uci', models.FloatField()),
                ('ethnicity_1000_pop', models.CharField(max_length=30)),
                ('REF_allele', models.CharField(max_length=30)),
                ('ALT_allele', models.CharField(max_length=30)),
                ('EFF_score', models.FloatField()),
                ('EFF_var', models.FloatField()),
                ('mtc_pvalue', models.FloatField()),
                ('SNP_risk', models.CharField(max_length=30)),
                ('SNP_test', models.CharField(max_length=30)),
                ('SNP_hyperlink', models.CharField(max_length=30)),
                ('gene_name', models.CharField(max_length=30)),
                ('gene_ensmbl_id', models.IntegerField()),
                ('gene_chr', models.CharField(max_length=30)),
                ('gene_band', models.CharField(max_length=30)),
                ('gene_start', models.IntegerField()),
                ('gene_end', models.IntegerField()),
                ('gene_risk_status', models.CharField(max_length=30)),
                ('gene_hyperlink', models.CharField(max_length=30)),
                ('disorder', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='analyzed',
            name='SNP_id',
        ),
        migrations.RemoveField(
            model_name='analyzed',
            name='study_id',
        ),
        migrations.RemoveField(
            model_name='features',
            name='gene_id',
        ),
        migrations.RemoveField(
            model_name='features',
            name='study_id',
        ),
        migrations.RemoveField(
            model_name='has_a',
            name='SNP_id',
        ),
        migrations.RemoveField(
            model_name='has_a',
            name='gene_id',
        ),
        migrations.RemoveField(
            model_name='related_to',
            name='SNP_id',
        ),
        migrations.RemoveField(
            model_name='related_to',
            name='disorder_id',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='id',
            new_name='study_id',
        ),
        migrations.DeleteModel(
            name='analyzed',
        ),
        migrations.DeleteModel(
            name='disorder',
        ),
        migrations.DeleteModel(
            name='features',
        ),
        migrations.DeleteModel(
            name='gene',
        ),
        migrations.DeleteModel(
            name='has_a',
        ),
        migrations.DeleteModel(
            name='related_to',
        ),
        migrations.DeleteModel(
            name='SNP',
        ),
        migrations.AddField(
            model_name='snp_entry',
            name='study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.study'),
        ),
    ]
