# Generated by Django 2.1.7 on 2019-10-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_auto_20190923_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snp_entry',
            old_name='enrty_id',
            new_name='entry_id',
        ),
    ]
