# Generated by Django 2.1.7 on 2019-10-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0005_join'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JOIN',
        ),
    ]
