# Generated by Django 2.1.7 on 2019-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_delete_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp_entry',
            name='ethnicity_1000_pop',
            field=models.CharField(choices=[('CHB', 'CHB'), ('JPT', 'JPT'), ('CHS', 'CHS'), ('CDX', 'CDX'), ('KHV', 'KHV'), ('CEU', 'CEU'), ('TSI', 'TSI'), ('FIN', 'FIN'), ('GBR', 'GBR'), ('IBS', 'IBS'), ('YRI', 'YRI'), ('LWK', 'LWK'), ('GWD', 'GWD'), ('MSL', 'MSL'), ('ESN', 'ESN'), ('ASW', 'ASW'), ('ACB', 'ACB'), ('MXL', 'MXL'), ('PUR', 'PUR'), ('CLM', 'CLM'), ('PEL', 'PEL'), ('GIH', 'GIH'), ('PJL', 'PJL'), ('BEB', 'BEB'), ('STU', 'STU'), ('ITU', 'ITU')], max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='DX',
            field=models.CharField(choices=[('C', 'C'), ('F', 'F'), ('B', 'B'), ('L', 'L')], max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='ascertainment',
            field=models.CharField(choices=[('African', 'African'), ('Ad Mixed American', 'Ad Mixed American'), ('East Asian', 'East Asian'), ('European', 'European'), ('South Asian', 'South Asian'), ('All', 'All')], max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='design',
            field=models.CharField(choices=[('GWA', 'GWA'), ('FBAT', 'FBAT'), ('Quantitative', 'Quantitative')], max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='source',
            field=models.CharField(choices=[('CL', 'CL'), ('PO', 'PO'), ('CO', 'CO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='test',
            field=models.CharField(choices=[('Allele codominant', 'Allele codominant'), ('Dominant', 'Dominant'), ('Recessive', 'Recessive'), ('Over-dominant', 'Over-dominant'), ('Additive', 'Additive')], max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='the_domain',
            field=models.CharField(choices=[('reading', 'reading'), ('speech', 'speech'), ('learning', 'learning')], max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='type_of_study',
            field=models.CharField(choices=[('GWAS', 'GWAS'), ('Chromosome #', 'Chromosome #'), ('Other', 'Other'), ('cSNP', 'cSNP'), ('Pooled', 'Pooled'), ('Candidate Gene', 'Candidate Gene')], max_length=30),
        ),
    ]
