# Generated by Django 2.1.7 on 2019-11-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0008_auto_20191113_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp_entry',
            name='Meta_p_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
