# Generated by Django 2.1.7 on 2019-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0009_auto_20191113_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp_entry',
            name='EFF_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='EFF_var',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='SNP_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='ethnicity_1000_pop',
            field=models.CharField(blank=True, choices=[('CHB', 'CHB'), ('JPT', 'JPT'), ('CHS', 'CHS'), ('CDX', 'CDX'), ('KHV', 'KHV'), ('CEU', 'CEU'), ('TSI', 'TSI'), ('FIN', 'FIN'), ('GBR', 'GBR'), ('IBS', 'IBS'), ('YRI', 'YRI'), ('LWK', 'LWK'), ('GWD', 'GWD'), ('MSL', 'MSL'), ('ESN', 'ESN'), ('ASW', 'ASW'), ('ACB', 'ACB'), ('MXL', 'MXL'), ('PUR', 'PUR'), ('CLM', 'CLM'), ('PEL', 'PEL'), ('GIH', 'GIH'), ('PJL', 'PJL'), ('BEB', 'BEB'), ('STU', 'STU'), ('ITU', 'ITU')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='gene_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='gene_ensmbl_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='gene_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='mtc_pvalue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='odds_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='odds_risk_lci',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='odds_risk_uci',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
