# Generated by Django 2.1.7 on 2019-11-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0010_auto_20191113_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='Case_N',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='Case_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='Case_perc_fem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='Control_N',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='Control_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='Control_perc_fem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='SD_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mean_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='num_SNPs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='num_affected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='num_families',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='num_generations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='num_polys',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
