# Generated by Django 2.1.7 on 2019-11-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0011_auto_20191113_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='ascertainment',
            new_name='ethinic_Population',
        ),
        migrations.AddField(
            model_name='snp_entry',
            name='Author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='snp_entry',
            name='Year',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='snp_entry',
            name='gene_ensmbl_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
