# Generated by Django 2.1.7 on 2019-11-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0012_auto_20191113_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='ethinic_Population',
            new_name='ethnic_Population',
        ),
    ]
