# Generated by Django 2.1.7 on 2019-11-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0013_auto_20191113_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='DX',
            field=models.CharField(blank=True, choices=[('Clinical Diagnosis', 'Clinical Diagnosis'), ('Family Risk', 'Family Risk'), ('Behavioral Assessment', 'Behavioral Assessment'), ('Language Sample', 'Language Sample')], max_length=30),
        ),
    ]
