# Generated by Django 2.1.7 on 2019-11-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0014_auto_20191115_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='source',
            field=models.CharField(blank=True, choices=[('Clinic Based', 'Clinic Based'), ('Population Based', 'Population Based'), ('Community Based', 'Community Based')], max_length=30),
        ),
    ]
